export const EXTRINSIC_ARGS = {
  createDpo: ['name', 'target', 'managerSeats', 'baseFee', 'directReferralRate', 'end', 'referrer'],
  createMilestoneReward: ['tokenId', 'milestone', 'reward'],
  createTravelCabin: ['tokenId', 'name', 'depositAmount', 'bonusTotal', 'yieldTotal', 'maturity', 'stockpile'],
  dpoBuyDpoSeats: ['buyerDpoIdx', 'targetDpoIdx', 'numberOfSeats'],
  dpoBuyTravelCabin: ['buyerDpoIdx', 'travelCabinIdx'],
  issueAdditionalTravelCabin: ['travelCabinIdx', 'numberMore'],
  passengerBuyDpoSeats: ['targetDpoIdx', 'numberOfSeats', 'referrerAccount'],
  passengerBuyTravelCabin: ['travelCabinIdx'],
  releaseBonusFromDpo: ['dpoIdx'],
  releaseFareFromDpo: ['dpoIdx'],
  releaseMilestoneReward: ['tokenId'],
  releaseYieldFromDpo: ['dpoIdx'],
  withdrawFareFromTravelCabin: ['travelCabinIdx', 'travelCabinNumber'],
  withdrawYieldFromTravelCabin: ['travelCabinIdx', 'travelCabinNumber'],
}

export const ARGS_HUMAN = {
  tokenId: 'Token',
  milestone: 'Milestone',
  reward: 'Reward',
  name: 'Name',
  depositAmount: 'Deposit',
  bonusTotal: 'Bonus',
  yieldTotal: 'Yield',
  maturity: 'Maturity',
  stockpile: 'Inventory',
  travelCabinIdx: 'Cabin Id',
  travelCabinNumber: 'Cabin Number',
  target: 'Target',
  managerSeats: 'Manager Seats',
  baseFee: 'Base Fee',
  directReferralRate: 'Direct Referral Rate',
  end: 'Maturity',
  referrer: 'Referrer',
  buyerDpoIdx: 'Buyer DPO',
  targetDpoIdx: 'Target DPO',
  numberOfSeats: 'Seats',
  referrerAccount: 'Referrer',
  dpoIdx: 'DPO Id',
}

export const ARGS_HUMAN_APPROVED: { [key: string]: string } = {
  tokenId: 'Token',
  milestone: 'Milestone',
  reward: 'Reward',
  name: 'Name',
  depositAmount: 'Deposit',
  bonusTotal: 'Bonus',
  yieldTotal: 'Yield',
  maturity: 'Maturity',
  stockpile: 'Inventory',
  travelCabinIdx: 'Cabin Id',
  travelCabinNumber: 'Inventory Id',
  target: 'Target',
  managerSeats: 'Manager Seats',
  baseFee: 'Base Fee',
  directReferralRate: 'Direct Referral Rate',
  end: 'Maturity',
  referrer: 'Referrer',
  buyerDpoIdx: 'Buyer DPO',
  targetDpoIdx: 'Target DPO',
  numberOfSeats: 'Seats',
  referrerAccount: 'Referrer',
  dpoIdx: 'DPO Id',
}
