import { FlatCardPlate } from 'components/Card'
import { PageWrapper, SpacedSection, Wrapper } from 'components/Wrapper'
import React from 'react'
import Text, { Heading, SectionTitle } from '../../components/Text'

export default function Faq() {
  return (
    <PageWrapper style={{ width: '100%', maxWidth: '720px', justifyContent: 'center', alignItems: 'center' }}>
      <Wrapper
        style={{
          display: 'flex',
          width: '100%',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <FlatCardPlate style={{ textAlign: 'left' }}>
          <Heading>Frequently Asked Questions</Heading>
          <SpacedSection>
            <SectionTitle>How do I login to Spanner&apos;s DApp?</SectionTitle>
            <Text>
              Spanner is a decentralized application where you can login via supported crypto wallets. Spanner offers
              two options for wallets at the moment. First, we have our <b>custodial wallets</b>, any Ethereum wallets
              supported by WalletConnect, that have their keys generated by us given the public key associated to your
              Ethereum wallet. Second, we have Substrate compatiable wallets where you can manage your own keys. At the
              moment, the only ones supported are the universal signing browser extensions such as Polkadotjs and
              MathWallet. Once you have a wallet, you can click on <b>Connect to a Wallet</b> and select the appropriate
              wallet option.
            </Text>
          </SpacedSection>
          <SpacedSection>
            <SectionTitle>How do I get tokens on Spanner?</SectionTitle>
            <Text>
              Click on the <b>account</b> button in the navaigation control bar then <b>Bridge</b> in the Account page
              tabs. Follow the bridge instructions there to start moving tokens via our Ethereum-Spanner Bridge.
            </Text>
          </SpacedSection>
          <SpacedSection>
            <SectionTitle>How do I switch projects?</SectionTitle>
            <Text>
              Click on the settings button and under <b>Project Settings {'>'} Selected Projects</b>, you can select the
              project you want to filter the Spanner Dapp with.
            </Text>
          </SpacedSection>
          <SpacedSection>
            <SectionTitle>How do I switch chains?</SectionTitle>
            <Text>
              By the navigation bar, there is a button that shows you which chain network you are connected to. Click on
              the button for a popup to select another network. Just for reference, Spanner is the Spanner Mainnet and
              Hammer is the testnet.
            </Text>
          </SpacedSection>
          <SpacedSection>
            <SectionTitle>Starting a project on Spanner</SectionTitle>
            <Text>{'We will be releasing open project onboarding in a future release. Stayed tuned for more.'}</Text>
          </SpacedSection>
        </FlatCardPlate>
      </Wrapper>
    </PageWrapper>
  )
}
